version: 2.1

executors:
  go-docker:
    docker:
      - image: cimg/go:1.20

jobs:
  go-tests:
    executor: go-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Tests
          command: ./scripts/test.sh
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)

  go-lint:
    executor: go-docker
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2
      - run:
          name: Lint
          command: GOGC=10 ./bin/golangci-lint run -j 4 --timeout 5m --exclude "\.pb.*\.go" --exclude "_strings\.go" --exclude "_test\.go" --exclude "not checked.+Close" ./...

  helm-check:
    executor: go-docker
    steps:
      - checkout
      - run:
          name: Install Helm and kubeval
          command: |
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
            tar xf kubeval-linux-amd64.tar.gz
      - run:
          name: Helm Template Check
          command: helm template ./helm/draino/ | ./kubeval --strict

  push:
    executor: go-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login quay.io -u "$DOCKER_USERNAME" --password-stdin
            docker build -t quay.io/amis/draino:$(git rev-parse --short HEAD) .
            docker push quay.io/amis/draino:$(git rev-parse --short HEAD)

  push-release:
    executor: go-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Release Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login quay.io -u "$DOCKER_USERNAME" --password-stdin
            docker pull quay.io/amis/draino:$(git rev-parse --short HEAD)
            docker tag quay.io/amis/draino:$(git rev-parse --short HEAD) quay.io/amis/draino:$(git describe --exact-match --tags)
            docker push quay.io/amis/draino:$(git describe --exact-match --tags)

workflows:
  version: 2
  test-and-push:
    jobs:
      - go-tests
      - go-lint
      - helm-check
      - push:
          requires:
            - go-tests
            - go-lint
            - helm-check
  release:
    jobs:
      - push-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+/
