{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "draino.serviceAccountName" . }}
  annotations:
    {{- toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ include "draino.name" . }}
    helm.sh/chart: {{ include "draino.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
